# autogenerated, do not edit 
ccflags-y += -Wno-unused-function -Wno-unused-label -Wno-unused-variable 
obj-m += ./deferred_work/6-kthread/
obj-m += ./lab5/pingpong/
obj-m += ./lab5/baby_io_uring/
obj-m += ./kernel_modules/7-list-proc/
obj-m += ./kernel_modules/1-2-test-mod/
obj-m += ./lab4/kernelJIT/
obj-m += ./kernel_api/4-list/
obj-m += ./kernel_api/3-memory/
obj-m += ./interrupts/
obj-m += ./memory_mapping/vmmap/
obj-m += ./memory_mapping/kmmap/
